// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@types+node@20.19.27_@vue+compiler-sfc@3.5.26_eslint@8.57.1_sass@1.97.1_typescrip_u43ajdg75if4vtvsw76q2vx46u/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@types+node@20.19.27_@vue+compiler-sfc@3.5.26_eslint@8.57.1_sass@1.97.1_typescrip_u43ajdg75if4vtvsw76q2vx46u/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@types+node@20.19.27_@vue+compiler-sfc@3.5.26_eslint@8.57.1_sass@1.97.1_typescrip_u43ajdg75if4vtvsw76q2vx46u/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@types+node@20.19.27_@vue+compiler-sfc@3.5.26_eslint@8.57.1_sass@1.97.1_typescrip_u43ajdg75if4vtvsw76q2vx46u/node_modules/nuxt/dist/app/plugins/payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@types+node@20.19.27_@vue+compiler-sfc@3.5.26_eslint@8.57.1_sass@1.97.1_typescrip_u43ajdg75if4vtvsw76q2vx46u/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@types+node@20.19.27_@vue+compiler-sfc@3.5.26_eslint@8.57.1_sass@1.97.1_typescrip_u43ajdg75if4vtvsw76q2vx46u/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@types+node@20.19.27_@vue+compiler-sfc@3.5.26_eslint@8.57.1_sass@1.97.1_typescrip_u43ajdg75if4vtvsw76q2vx46u/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@types+node@20.19.27_@vue+compiler-sfc@3.5.26_eslint@8.57.1_sass@1.97.1_typescrip_u43ajdg75if4vtvsw76q2vx46u/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@types+node@20.19.27_@vue+compiler-sfc@3.5.26_eslint@8.57.1_sass@1.97.1_typescrip_u43ajdg75if4vtvsw76q2vx46u/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@hebilicious+vue-query-nuxt@0.3.0_@tanstack+vue-query@5.92.1_nuxt@3.20.2/node_modules/@hebilicious/vue-query-nuxt/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../app/plugins/vue-gtm.client")> &
  InjectionType<typeof import("../../app/plugins/vue-query")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:prefetch'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
