// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/23/2025, 9:41:21 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/project/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/app/plugins/**/*.{js,ts,mjs}","/home/project/app/composables/**/*.{js,ts,mjs}","/home/project/app/utils/**/*.{js,ts,mjs}","/home/project/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/project/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/project/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;