export { useScriptTriggerConsent, useScriptEventPage, useScriptTriggerElement, useScript, useScriptGoogleAnalytics, useScriptPlausibleAnalytics, useScriptCrisp, useScriptClarity, useScriptCloudflareWebAnalytics, useScriptFathomAnalytics, useScriptMatomoAnalytics, useScriptGoogleTagManager, useScriptGoogleAdsense, useScriptSegment, useScriptMetaPixel, useScriptXPixel, useScriptIntercom, useScriptHotjar, useScriptStripe, useScriptLemonSqueezy, useScriptVimeoPlayer, useScriptYouTubePlayer, useScriptGoogleMaps, useScriptNpm, useScriptUmamiAnalytics, useScriptSnapchatPixel, useScriptRybbitAnalytics, useScriptDatabuddyAnalytics, useScriptRedditPixel, useScriptPayPal } from '#app/composables/script-stubs';
export { isVue2, isVue3 } from 'vue-demi';
export { defineNuxtLink } from '#app/components/nuxt-link';
export { useNuxtApp, tryUseNuxtApp, defineNuxtPlugin, definePayloadPlugin, useRuntimeConfig, defineAppConfig } from '#app/nuxt';
export { useAppConfig, updateAppConfig } from '#app/config';
export { defineNuxtComponent } from '#app/composables/component';
export { useAsyncData, useLazyAsyncData, useNuxtData, refreshNuxtData, clearNuxtData } from '#app/composables/asyncData';
export { useHydration } from '#app/composables/hydrate';
export { callOnce } from '#app/composables/once';
export { useState, clearNuxtState } from '#app/composables/state';
export { clearError, createError, isNuxtError, showError, useError } from '#app/composables/error';
export { useFetch, useLazyFetch } from '#app/composables/fetch';
export { useCookie, refreshCookie } from '#app/composables/cookie';
export { onPrehydrate, prerenderRoutes, useRequestHeader, useRequestHeaders, useResponseHeader, useRequestEvent, useRequestFetch, setResponseStatus } from '#app/composables/ssr';
export { onNuxtReady } from '#app/composables/ready';
export { preloadComponents, prefetchComponents, preloadRouteComponents } from '#app/composables/preload';
export { abortNavigation, addRouteMiddleware, defineNuxtRouteMiddleware, setPageLayout, navigateTo, useRoute, useRouter } from '#app/composables/router';
export { isPrerendered, loadPayload, preloadPayload, definePayloadReducer, definePayloadReviver } from '#app/composables/payload';
export { useLoadingIndicator } from '#app/composables/loading-indicator';
export { getAppManifest, getRouteRules } from '#app/composables/manifest';
export { reloadNuxtApp } from '#app/composables/chunk';
export { useRequestURL } from '#app/composables/url';
export { usePreviewMode } from '#app/composables/preview';
export { useRouteAnnouncer } from '#app/composables/route-announcer';
export { useRuntimeHook } from '#app/composables/runtime-hook';
export { useHead, useHeadSafe, useServerHeadSafe, useServerHead, useSeoMeta, useServerSeoMeta, injectHead } from '#app/composables/head';
export { onBeforeRouteLeave, onBeforeRouteUpdate, useLink } from 'vue-router';
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, watchPostEffect, watchSyncEffect, onWatcherCleanup, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, hasInjectionContext, nextTick, provide, toValue, useModel, useAttrs, useCssModule, useCssVars, useSlots, useTransitionState, useId, useTemplateRef, useShadowRoot, Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue';
export { requestIdleCallback, cancelIdleCallback } from '#app/compat/idle-callback';
export { definePageMeta } from '../node_modules/.pnpm/nuxt@3.20.2_@types+node@20.19.27_@vue+compiler-sfc@3.5.26_eslint@8.57.1_sass@1.97.1_typescrip_u43ajdg75if4vtvsw76q2vx46u/node_modules/nuxt/dist/pages/runtime/composables';
export { defineLazyHydrationComponent } from '#app/composables/lazy-hydration';
export { API_ENDPOINTS, useAPI, useFindMany, useDocuments, useSearch, useQueryParam, EndpointToFindOneTypeMap, EndpointToPaginatedTypeMap, ExtractItemType, ExtractPaginatedItemType } from '../app/composables/api';
export { DefaultMagicItemFilter, MAGIC_ITEMS_RARITES, MAGIC_ITEMS_TYPES, MagicItemFilter } from '../app/composables/magic-items';
export { DefaultMonsterFilter, useMonster, MONSTER_CHALLENGE_RATINGS_LIST, MONSTER_CHALLENGE_RATINGS_MAP, MONSTER_SIZES_LIST, MONSTER_TYPES_LIST, MonsterFilter } from '../app/composables/monsters';
export { useAllSpells, SPELL_LEVELS_NAMES, useFormatSpellSubtitle, DefaultSpellFilter, copySpellFilter, SpellFilter } from '../app/composables/spells';
export { useBreadcrumbs } from '../app/composables/useBreadcrumbs';
export { useBreakpoints } from '../app/composables/useBreakpoints';
export { useDiceRoller } from '../app/composables/useDiceRoller';
export { useEncounterStore, DifficultyLevel, EncounterMonster } from '../app/composables/useEncounter';
export { useFilterState, Fields, FilterStateOptions, FilterState } from '../app/composables/useFilterState';
export { useFindOne } from '../app/composables/useFindOne';
export { useFindPaginated } from '../app/composables/useFindPaginated';
export { useFormatModifier } from '../app/composables/useFormatModifier';
export { useNotifications } from '../app/composables/useNotifications';
export { usePageMetadata, usePageTitle } from '../app/composables/usePageMetadata';
export { usePartyStore } from '../app/composables/useParty';
export { useSortState } from '../app/composables/useSortState';
export { setSources, read_only_source_list, useSourcesList } from '../app/composables/useSourcesList';
export { useThemeSwitcher, Theme } from '../app/composables/useThemeSwitcher';
export { useXPCalculator } from '../app/composables/useXPCalculator';
export { defineVueQueryPluginHook } from '../node_modules/.pnpm/@hebilicious+vue-query-nuxt@0.3.0_@tanstack+vue-query@5.92.1_nuxt@3.20.2/node_modules/@hebilicious/vue-query-nuxt/dist/runtime/composables/defineVueQueryPluginHook';
export { useQuery, useQueries, useInfiniteQuery, useMutation, useIsFetching, useIsMutating, useQueryClient } from '@tanstack/vue-query';
export { useNuxtDevTools } from '../node_modules/.pnpm/@nuxt+devtools@3.1.1_vite@7.3.0_vue@3.5.26/node_modules/@nuxt/devtools/dist/runtime/use-nuxt-devtools';